# Generated by Django 4.2 on 2024-03-09 09:49

import data.models
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='site url address', verbose_name='url')),
                ('name', models.CharField(blank=True, help_text='site name', max_length=64, verbose_name='name')),
                ('slogan', models.CharField(blank=True, help_text='site slogan', max_length=256, verbose_name='slogan')),
                ('banner', models.ImageField(blank=True, help_text='website header banner image', upload_to=data.models.banner_path, verbose_name='website banner image')),
                ('email', models.EmailField(blank=True, help_text='email contact', max_length=64, verbose_name='email')),
                ('telegram', models.CharField(blank=True, help_text='telegram contact', max_length=64, verbose_name='telegram')),
                ('phone', models.CharField(blank=True, help_text='phone contact number', max_length=18, null=True, unique=True, validators=[users.models.phone_validator], verbose_name='phone number')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='address')),
            ],
        ),
    ]
